---
title: Drumson
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: American producer and drummer in Germany
baseurl: ''
url: ''
twitter_username: 
github_username: 
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
- jekyll-feed
